on:
  push:

name: CI

jobs:

  build_and_test:
    name: Build and test
    runs-on: ubuntu-24.04
    container: rust:1.70
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --all-features
      - run: cargo test --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.84
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    container: rust:1.84
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
